export {
  AgentsNamespace,
  CapabilitiesNamespace,
  HandStack,
  ModelsNamespace,
  OpenAiChatNamespace,
  OpenAiCompletionsNamespace,
  OpenAiEmbeddingsNamespace,
  OpenAiModelsNamespace,
  OpenAiNamespace,
  type ChatCompletion,
  type ChatCompletionChunk,
  type ChatCompletionChoice,
  type ChatCompletionRequest,
  type ChatMessage,
  type CreateAgentInput,
  type CreateAgentVersionInput,
  type EmbeddingRequest,
  type EmbeddingResponse,
  type FetchLike,
  type HandStackClientOptions,
  type HandStackRequestOptions,
  type ListResponse,
  type ModelEntry,
  type ModelResponse,
  type ModelResponseRequest,
  type ModelsListResponse,
  type NeutralChatMessage,
  type NeutralTool,
} from './client.js';
export {
  HandStackApiError,
  HandStackSdkError,
  isProblemDetails,
  type HandStackProblemDetails,
} from './errors.js';
export { parseSse, type SseEvent } from './sse.js';
